Add sonarqube scan to test workflow
populationgenomics/cpg-utils pull request #173
Opened 2024-09-14 07:42 UTC by violetbrina

2024-09-18 23:57 UTC, nevoodoo requested changes

2024-09-18 23:57 UTC, nevoodoo commented on .github/workflows/test.yaml
> +        coverage run -m pytest/ --junitxml=test-execution.xml
Maybe there's a typo here with the extra slash? Might be causing the error

2024-09-19 00:38 UTC, violetbrina commented on .github/workflows/test.yaml
> +        coverage run -m pytest/ --junitxml=test-execution.xml
Fixed!

2024-09-19 01:04 UTC, nevoodoo approved these changes

2024-09-20 06:39 UTC, merged

2024-09-22 22:06 UTC, jmarshall commented
I realise I am late to the party, but: What is the reason for removing codecov?

2024-09-23 04:54 UTC, violetbrina commented
Mostly that it's totally redundant. I didn't see much point in keeping it around if the coverage is in sonarqube anyway.