Add web_url
populationgenomics/cpg-utils pull request #37
Opened 2022-05-18 23:20 UTC by vladsaveliev

Add function to get CPG web URL.

Make sure to merge https://github.com/populationgenomics/cpg-utils/pull/36 first

2022-05-18 23:22 UTC, vivbak approved these changes
🙏  Thanks!!

2022-05-18 23:25 UTC, lgruen requested changes

2022-05-18 23:25 UTC, lgruen commented on cpg_utils/hail_batch.py
> +WEB_URL_FORMAT = 'https://{namespace}-web.populationgenomics.org.au/{dataset}'
Should we make this configurable or will `web_url` only be called for CPG-internal implementations?

2022-05-18 23:50 UTC, vladsaveliev commented on cpg_utils/hail_batch.py
> +WEB_URL_FORMAT = 'https://{namespace}-web.populationgenomics.org.au/{dataset}'
Currently in the cpg-pipes, `CpgStorageProvider` uses the `web_url` function from cpg_utils, and the abstract one doesn't have a default implementation.

But if we are getting rid of those abstractions and relying entirely on the toml config to configure the environment, then we should somehow explain that the WEB_URL_FORMAT should be parametrised by namespace and dataset. It's straightforward to put such requirements with abstract classes, but a bit more error-prone with a string template like that. But could add `web_url_template` into the toml config with a comment.

2022-05-19 01:17 UTC, vladsavelyev commented on cpg_utils/hail_batch.py
> +WEB_URL_FORMAT = 'https://{namespace}-web.populationgenomics.org.au/{dataset}'
Added a commit to parametrise it with an environment variable

2022-05-19 03:54 UTC, lgruen approved these changes

2022-05-19 07:36 UTC, merged